server.port=8761
spring.application.name=eureka-server


# Disable client registration with Eureka, as this is just the registry
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Enable self-preservation mode for Eureka server (optional)
eureka.server.enable-self-preservation=false
